---
- project:
    check:
      jobs:
        - ansible-buildset-registry
        - network-ee-build-container-image
        - network-ee-sanity-tests
        - network-ee-unit-tests
        - network-ee-build-container-image-stable-2.9
        - network-ee-sanity-tests-stable-2.9
        - network-ee-unit-tests-stable-2.9
